version: '3.8'

services:
  nse-data-scraper:
    build: .
    container_name: nse-data-scraper
    restart: unless-stopped
    ports:
      - "6002:6002"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://akash9936:Tree9936@cluster0.f1wthph.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      - mongodb
    networks:
      - nse-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - nse-network

networks:
  nse-network:
    driver: bridge

volumes:
  mongodb-data: