name: Scheduled Notification

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script
        run: |
          node ./src/models/getNSEIndiaData.js  # Your script to send notifications
